### ISSUE TITLE
H3 Paragraph on WYSIWYG

### ISSUE THREAD

**Issue by reraxe** [CorentinTh/it-tools#1342]
### Describe the bug

Selecting H3 paragraph also selects H4. Making the selected H3 to H4 on HTML

### What happened?

![image](https://github.com/user-attachments/assets/4ea66364-1cfe-42db-83c0-3d69e3c2af01)

### System information

linux

### Where did you encounter the bug?

Public app (it-tools.tech)

**Comment by gitmotion** [comment]
@reraxe fixed this in PR: https://github.com/CorentinTh/it-tools/pull/1363

![demo](https://github.com/user-attachments/assets/018943df-78bd-4070-b95c-fd3ef29d0db8)
##
Since PRs are a bit backed up on https://github.com/CorentinTh/it-tools you can use my image in your docker-compose file if you want this functionality along with my other additions until the main branch has been updated:
#### added features
- reorder favorites with drag and drop: (https://github.com/CorentinTh/it-tools/pull/1360)
- AI prompt splitter: (https://github.com/CorentinTh/it-tools/pull/1357)
- multi-link downloader: (https://github.com/CorentinTh/it-tools/pull/1354)
- image resizer: (https://github.com/CorentinTh/it-tools/pull/1361)
- JSON String converter: (https://github.com/CorentinTh/it-tools/pull/1351)
**docker image:**
```
ghcr.io/gitmotion/it-tools:latest
```
- you may need to clear cache and hard reload to get new features loading

#### OR locally
**from github repo (copy & paste oneliner):**
```
git clone -b gitmotion/main https://github.com/gitmotion/it-tools.git && cd it-tools/ && pnpm i && pnpm dev
``` 
- (installing packages for the first time may take some time but wait till it finishes)
##
