### ISSUE TITLE
[FEAT] API for tools

### ISSUE THREAD

**Issue by cakee-ru** [CorentinTh/it-tools#295]
**Is your feature request related to a problem? Please describe.**
this thing is awesome already, but it'd be 10 times more useful if it had an HTTP API so anyone could integrate this into shell scripts or apps.

**Describe the solution you'd like**
HTTP API which could be used i.e. with Curl.

**Describe alternatives you've considered**
none

**Additional context**
I haven't found any info about API. if it already exist, correct me please.

**Comment by CorentinTh** [comment]
Hi @cakee-ru 

Thank you for your interest in this project and for your kind words

Unfortunately, we cannot yet provide an API to it tools since the app is built using static HTML, CSS, and JavaScript (it's client side Vue js). APIs require server-side code, which is not the case with this app. 

However, we appreciate your input and encourage you to continue exploring it-tools 🙏🏻
