### ISSUE TITLE
[BUG] Wrong User-agent parser values

### ISSUE THREAD

**Issue by nickm324** [CorentinTh/it-tools#340]
**Which tool is impacted?**
User-agent parser

**To Reproduce**

1. click the User-agent parser

**Expected behavior**
Expected specific results for OS and CPU.
Totally inaccurate results. Says OS is Windows 10 and CPU is AMD, neither is correct.
PC is Windows 11 and Intel 12900K CPU.

**Screenshots**
![image](https://user-images.githubusercontent.com/6774571/230603338-2c321579-995f-4dc9-8b8f-9548017804b1.png)

**Configuration (please complete the following information):**

- Device: Windows PC
- OS: Windows 11
- Browser: Chrome
- Version : 111

**Additional context**
Guess this could be blamed on the browser and the user agent string its providing, but even if that is the case what use is parser that will always provide the wrong information.

**Comment by CorentinTh** [comment]
Hi thank you for submiting this bug

But its the expected behavior .

You won't be able to detect Windows 11 because Windows 11 will use "Window NT 10.0" which is the same that Windows 10 uses.

But for the cpu it's correct, intel cpu uses the amd64 architecture (it has nothing to do with the AMD cpu brand)

**Comment by nickm324** [comment]
Ok, well all though all that may be correct, what is the point then if you are not going to get the expected results. I guess the question is what's the advantage of this tool if it can't detect windows 11 or report whether I have an actual AMD or INTEL CPU?

**Comment by CorentinTh** [comment]
The goal of this tool is to parse user agent, not to magically guess from where it come
Thus using the User-Agent string to detect the browser and operating system is not reliable and is a legacy practice. 

So if your UA is incorrect it's the fault of your UA provider (your browser), not the parser.

**Regarding the CPU**
The term "amd64" in a user agent string refers to the x86-64 architecture, which is also commonly known as "Intel 64" or "x64". This architecture was developed by AMD, but it is also used by Intel and other processor manufacturers.

The confusion arises because the term "amd64" has become the de facto standard name for the x86-64 architecture, even though it was originally developed and marketed by AMD. This is similar to how "Intel Inside" became a generic term for personal computers with Intel processors, even though other manufacturers also produce computers with Intel processors.

So, when you see "amd64" in a user agent string for an Intel processor, it simply means that the processor is using the x86-64 architecture, which is compatible with both AMD and Intel processors.
