### ISSUE TITLE
[New Tool] DNS Lookup

### ISSUE THREAD

**Issue by ryanvanmass** [CorentinTh/it-tools#412]
**What tool do you want?**

The ability to look up dns registry/entry information. ie the output of `whois`

**Describe the solution you'd like**

A simple feild to enter a domain name and then the output of the whois command

**Is their example of this tool in the wild?**
https://www.whois.com/whois

**Comment by CorentinTh** [comment]
Hello @ryanvanmass 

Thanks heaps for suggesting the idea of a DNS lookup tool for it-tools. It's a super cool feature idea and we totally get why it'd be handy for devs and IT folks.

But here's the thing, it-tools runs strictly client-side. This means it can't directly make DNS lookups or Whois queries without getting some external server or API involved. It's a bit of a bummer, I know. This stuff needs server-side execution because they're about firing network requests to domain servers or Whois databases. Browsers don't let these operations go through from the user's side for security reasons.

We want to keep it-tools lightweight, free from reliance on external services or APIs. It's all about ensuring user privacy and making sure our app's performance isn't tied to anything outside.

So, while your suggestion was totally worth considering, we unfortunately won't be able to roll it in. But hey, don't let this stop you! If you have more ideas that would work within the client-side environment, we'd love to hear them.

**Comment by sharevb** [comment]
Hi @ryanvanmass  and @CorentinTh, DNS queries over HTTPS implemented in https://github.com/CorentinTh/it-tools/pull/1371
