### ISSUE TITLE
[OTHER]  Add IP address of user in Device Information

### ISSUE THREAD

**Issue by roland-d** [CorentinTh/it-tools#415]
**Describe the solution you'd like**
On the `Device information` page it would be nice to also show the users IP address.

**Additional context**
The reason for this request is that often I need to check what my IP address is and I can never remember what it is :) This way it is a quick way to check. I need to check this to add it to htaccess files for example.

**Comment by CorentinTh** [comment]
Hello @roland-d 

Thanks for suggesting the idea of an ip lookup tool in the device information. It's a super cool feature idea and we totally get why it'd be handy for devs and IT folks.

But here's the thing, it-tools runs strictly client-side. This means it can't directly make ip lookups queries without getting some external server or API involved. It's a bit of a bummer, I know. This stuff needs server-side execution because they're about firing network requests to to a server. Browsers don't let these operations go through from the user's side for security reasons.

We want to keep it-tools lightweight, free from reliance on external services or APIs. It's all about ensuring user privacy and making sure our app's performance isn't tied to anything outside.

So, while your suggestion was totally worth considering, we unfortunately won't be able to roll it in. But hey, don't let this stop you! If you have more ideas that would work within the client-side environment, we'd love to hear them.
