### ISSUE TITLE
[BUG] IPv4 Address Converter does not allow the user to change the example IP

### ISSUE THREAD

**Issue by luketainton** [CorentinTh/it-tools#436]
**Which tool is impacted?**
IPv4 Address Converter

**To Reproduce**

1. Deploy self-hosted application
2. Go to affected tool
3. Attempt to change example IP address

**Expected behavior**
The user should be able to change the example IP address.

**Server Configuration:**
- Device: Synology NAS
- OS: Synology DSM
- Version: DSM 7.1.1-42962 Update 5

**Client Configuration:**
- Device: MacBook Pro
- OS: MacOS Ventura 13.4
- Browser: Microsoft Edge Dev
- Version: 115.0.1880.3

**Additional context**
This is a fresh deployment of the application.

**Comment by cgoIT** [comment]
Hi @luketainton, 
I've testet this on nearly the same client infrastructure. Not with Microsoft Edge but with chrome, firefox and safari. On the server I'm using version [v2023.5.14-77f2efc](https://github.com/CorentinTh/it-tools/tree/v2023.5.14-77f2efc).

For me I can't reproduce the bug you described. Maybe you can try to reproduce the bug on the [official demo](https://it-tools.tech) to see, if the error is still there. If so, it must be something related to your client. Maybe you can try to use a different browser for testing or you have a look at the javascript console if there is an error.

If the error is not there with the official demo it must have something to do with your server installation (or network). But I don't think that this is the case because it-tools work fully client side.

**Comment by luketainton** [comment]
Hey @cgoIT,

I tried to reproduce on the official demo and couldn't either, however, I tried multiple browsers on my deployment and hit the bug in all of them.

I'll have another look into my config just to confirm.

**Comment by kmanwar89** [comment]
I spun this up and was also able to reproduce this behavior - the IPv4 address field is not editable, and editing any of the other fields doesn't reflect the change in the IPv4 field.

Relevant details:

**Server Configuration:**

    Device: Dell Laptop
    OS: Ubuntu Server
    Version: 22.04.2 LTS
    IT-Tools v2023.5.14-77f2efc

Client Configuration:

    Device: Desktop
    OS: Pop!_OS 22.04 LTS
    Browser: Firefox in Incognito Mode, Brave Browser (chromium-based)
    Version: Firefox: 114.0, Brave: 1.52.117, Chromium 114.0.5735.90
    
    
Since no compose file is provided, I adapted the docker-run commands as follows, and the container is only one of 2 running, both with bridged docker networks

```
version: '3.3'
services:
  app:
    ports:
      - '8080:80'
    container_name: it-tools
    image: corentinth/it-tools
```

**Comment by CorentinTh** [comment]
Thank you all for the investigation 🙏🏻 
A possible cause for this issue is the default values for the props of the text input not taken in account, fixing this in #448, tell me if this fixes the issue

**Comment by luketainton** [comment]
Hey @CorentinTh - did your merge to `main` automatically build/push a new Docker image? I pulled fresh from Docker Hub but the version number hasn't changed and the issue is still present.

**Comment by CorentinTh** [comment]
It was indeed on the nightly image
Thanks for the update @luketainton 🙏🏻
